#!/bin/bash

# Set your MongoDB and S3 credentials
MONGO_USER="mongodbadmin"
MONGO_AUTH_DB="admin"
MONGO_PASSWORD="rara@db@dmin"
S3_BUCKET="s3://rara-backup/prod_mongo/"
LOG_PATH="/opt/mongodump.log"

# Create a timestamp for the dump file
TIMESTAMP=$(date +"%y-%m-%d")

# Define the dump file name
DUMP_FILE="$TIMESTAMP-prod-mongo.tar"

# Perform the MongoDB dump
mongodump --archive="$DUMP_FILE" --username="$MONGO_USER" --authenticationDatabase="$MONGO_AUTH_DB" --password="$MONGO_PASSWORD"

# Check if the dump was successful
if [ $? -eq 0 ]; then
  echo "MongoDB dump completed successfully"
  
  # Transfer the dump to S3
  aws s3 cp "$DUMP_FILE" "$S3_BUCKET" >> "$LOG_PATH"
  
  # Check if the S3 transfer was successful
  if [ $? -eq 0 ]; then
    echo "MongoDB dump successfully transferred to S3"
  else
    echo "Failed to transfer dump to S3" >> "$LOG_PATH"
  fi
  
  # Clean up the local dump file
  rm -f "$DUMP_FILE"
else
  echo "MongoDB dump failed" >> "$LOG_PATH"
fi

